### ISSUE TITLE
Use of functools.partial in tutorial may be confusing

### ISSUE THREAD

**Issue by PyryM** [WatchBeam/developers#117]
In gitter chat several people were confused by the use of `partial(print, "RECEIVE: ")` as a [callback in the chatbot tutorial](https://github.com/WatchBeam/developers/blob/b175b763f4778e0489f407203276cf4ccc74318b/src/tutorials/code/python/chat/5.py#L16). Since these tutorials are used by people of all experience levels, for clarity it might make sense to define the callback with a normal named function.

**Comment by ProbablePrime** [comment]
Landed with: https://github.com/WatchBeam/developers/commit/5ebe72c614fb5a2333a337f320c68edda73f65c6
