### ISSUE TITLE
A better interactive tutorial? 

### ISSUE THREAD

**Issue by madmax345** [WatchBeam/developers#136]
I wouldn't call myself a good developer, I just love making stuff.. 
The beam tutorial https://dev.beam.pro/tutorials/interactive.html is a little confusing. 

Any other tutorials to get me going? 

Thanks!

**Comment by connor4312** [comment]
Hi madmax,

We're actually working on a major revision to Interactive right now; although the current system will continue to run and you'll be able to build stuff for it, we'll be updating our tutorials to the new version soon! If you'd like some help getting started I recommend that you hop in our Gitter channel here: https://gitter.im/WatchBeam/developers
