### ISSUE TITLE
Isomorphic views

### ISSUE THREAD

**Issue by ttaylorr** [WatchBeam/developers#31]
Problem: the developers site as it stands is pretty static.  Views are rendered on the backend (which is cool) but they are not rendered on the frontend whatsoever since React.js the library isn't sent down as a script.

Solution: make the code powering the developers site renderable both on the frontend and backend by bundling it correctly with Webpack and sending down it and the React.js library itself.  The steps to accomplish this task are outlined below, in the order in which they need to happen.

## Todo

- Replace Express with Hapi
- Move the server logic outside of the `src/` directory
- Webpack the "backend" (now isomorphic) code, send it down as an asset
- Send react.js down as an asset

**Comment by MCProhosting-Matt** [comment]
Why is this needed?

**Comment by ttaylorr** [comment]
Isn't currently, this is a "when we have time" sort of issue.

**Comment by MCProhosting-Matt** [comment]
We need a "weht" tag. :P @ttaylorr

**Comment by ttaylorr** [comment]
Is it OK if we still leave this open, @MCProhosting-Matt? This is still something that I want to address in the future.

**Comment by MCProhosting-Matt** [comment]
Discussed in Slack - may reopen at a later time pending Connor and the team's feedback
