### ISSUE TITLE
Pages that don't exist still return a 200 and are blank

### ISSUE THREAD

**Issue by MCProhosting-Matt** [WatchBeam/developers#39]
https://developer.beam.pro/api for example

**Comment by ttaylorr** [comment]
@Antariano Do you have time to send me a 404 page PSD?

**Comment by MCProhosting-Matt** [comment]
@ttaylorr Literally just a big white 404 in the middle with a back to home link should be fine.

**Comment by ttaylorr** [comment]
Will take care of this if I get the chance tonight!

**Comment by JamyDev** [comment]
Seems like @artdude543 took care of this already in his latest [commit](https://github.com/artdude543/developers/commit/47141bd2457aad45c263368f7d287350ad89caf8)
