### ISSUE TITLE
[Request] For api

### ISSUE THREAD

**Issue by TheBaconSpace** [WatchBeam/developers#68]
Can we have a api for to track lvls like how u got sparks so maybe like level:100 :+1:

**Comment by connor4312** [comment]
This has been a popular request... so sure, why not

**Comment by TheBaconSpace** [comment]
thanks since it would be a great feature for [BeamStats](http://streamstats.github.io/BeamStats) @connor4312

**Comment by SimonSchick** [comment]
This has been added and will be available soon.
